apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-bastion
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  containers:
  - command:
    - sleep
    - infinity
    image: ubuntu
    imagePullPolicy: Always
    name: ubuntu-bastion
    ports:
    - containerPort: 80
      protocol: TCP